package:
  name: cct
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build: &id1
    - {{ compiler('c') }}
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - numpy {{ numpy }}
    - cython >=0.15
    - matplotlib
    - scipy
    - sastool >=1.1.5
    - krb5
    - pyqt >=5
    - psutil
    - pymodbustcp
    - appdirs
    - pillow
    - openpyxl
    - sqlalchemy
    - adjusttext
    - imageio
    - click
    - colorlog
    - pyusb

  host: *id1

  run:
    - pillow
    - python
    - appdirs
    - numpy {{ numpy }}
    - pymodbustcp
    - psutil
    - krb5
    - scipy
    - matplotlib
    - sastool >=1.2.3
    - pyqt >=5
    - openpyxl
    - sqlalchemy
    - adjusttext
    - imageio
    - click
    - colorlog
    - pyusb

about:
  home: https://github.com/awacha/cct
  license: 3-clause BSD license
  dev_url: https://github.com/awacha/cct.git
  license_family: BSD
  license_file: LICENSE
  summary: DAQ for CREDO
  description: Instrument control and data acquisition software for the CREDO SAXS instrument

app:
  entry: cpt [win]
  summary: Credo Processing Tool
  type: desk
  icon: cptlogo.png

app:
  entry: cpt2 [win]
  summary: Credo Processing Tool v2
  type: desk
  icon: cpt2logo.png
