package:
  name: cct
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build: &id1
    - {{ compiler('c') }}
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - numpy {{ numpy }}
    - cython >=0.15
    - matplotlib
    - scipy
    - krb5
    - pyqt >=5
    - psutil
    - appdirs
    - pillow
    - openpyxl
    - sqlalchemy
    - adjusttext
    - imageio
    - click
    - colorlog

  host: *id1

  run:
    - pillow
    - python
    - appdirs
    - numpy {{ numpy }}
    - psutil
    - krb5
    - scipy
    - matplotlib
    - pyqt >=5
    - openpyxl
    - sqlalchemy
    - adjusttext
    - imageio
    - click
    - colorlog

about:
  home: https://github.com/awacha/cct
  license: 3-clause BSD license
  dev_url: https://github.com/awacha/cct.git
  license_family: BSD
  license_file: LICENSE
  summary: DAQ for CREDO
  description: Instrument control and data acquisition software for the CREDO SAXS instrument
